//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularMultipleScren.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int UserId { get; set; }
        public string RefreshToken { get; set; }
        public string GmailId { get; set; }
    }
}
